title: Let's learn something!
author: Deep Sukhwani
email: Deep Sukhwani
description: > # this means to ignore newlines until "baseurl:"
  Will try to learn something new to keep ourselves updated, growing and enjoy the overall learning process

# social links
twitter_username: deepsukhwani # DO NOT include the @ character, or else the build will fail!
github_username:  proprogrammer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# view
theme: minima
